### ISSUE TITLE
Serving app under subdirectory not working

### ISSUE THREAD

**Issue by adjokic** [linuxserver/docker-babybuddy#16]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Serving under a subdirectory doesn't work in the docker container.
------------------------------

## Expected Behavior

babybuddy should be served from /babybuddy, e.g. http://myserver:8000/babybuddy

## Current Behavior

babybuddy is still being served from the root directory, e.g. http://myserver:8000/

## Steps to Reproduce

1. Follow the instructions [here](https://docs.baby-buddy.net/setup/subdirectory/) and add SUB_PATH=/babybuddy to the docker container
2. `docker-compose stop babybuddy`
3. `docker-compose start babybuddy`

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

## Command used to create docker container (run/create/compose/screenshot)

```
version: "2.1"
services:
  babybuddy:
    image: lscr.io/linuxserver/babybuddy
    container_name: babybuddy
    environment:
      - TZ=UTC
      - SUB_PATH=/babybuddy
      - USE_24_HOUR_TIME_FORMAT=true
    volumes:
      - ~/docker-data/babybuddy:/config
    ports:
      - 8000:8000
    restart: unless-stopped
```
## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 02-tamper-check: executing...
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
BabyBuddy: https://github.com/sponsors/cdubz

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
Operations to perform:
  Apply all migrations: admin, auth, authtoken, axes, babybuddy, contenttypes, core, sessions
Running migrations:
  No migrations to apply.
  Your models in app(s): 'babybuddy' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
Cache table 'cache_default' already exists.
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-03-26 21:44:55 -0500] [301] [INFO] Starting gunicorn 20.1.0
[2022-03-26 21:44:55 -0500] [301] [INFO] Listening at: http://0.0.0.0:8000 (301)
[2022-03-26 21:44:55 -0500] [301] [INFO] Using worker: gthread
[2022-03-26 21:44:55 -0500] [317] [INFO] Booting worker with pid: 317
[2022-03-26 21:44:55 -0500] [318] [INFO] Booting worker with pid: 318
```

**Comment by adjokic** [comment]
fwiw, I tried
```
sed -i "s|location ^~ /static/|location ^~ ${SUB_PATH}/static/|g" /app/babybuddy/etc/nginx.conf
sed -i "s|location /|location ${SUB_PATH}|g" /app/babybuddy/etc/nginx.conf
```
which didn't seem to do the trick either. This is what my nginx.conf looks like after running the above:
```
worker_processes 1;
daemon off;

events {
    worker_connections 1024;
}

http {
    include /data/etc/nginx/mime.types;
    sendfile on;

    gzip              on;
    gzip_http_version 1.0;
    gzip_proxied      any;
    gzip_min_length   500;
    gzip_disable      "MSIE [1-6]\.";
    gzip_types        text/plain text/xml text/css
                      text/comma-separated-values
                      text/javascript
                      application/x-javascript
                      application/atom+xml;

    # Proxy upstream to the gunicorn process
    upstream django {
        server 127.0.0.1:8000;
    }

    # Configuration for Nginx
    server {

        # Listen on port 8080
        listen 8080;

        # Settings to serve static files
        location ^~ /babybuddy/static/  {
            root /app/;
        }

        # Serve a static file (ex. favico)
        # outside /static directory
        location = /favico.ico  {
            root /app/favico.ico;
        }

        # Proxy connections to django
        location /babybuddy {
            proxy_pass         http://django;
            proxy_redirect     off;
            proxy_set_header   Host $host;
        }
    }
}
```

**Comment by aptalca** [comment]
Our image doesn't use nginx. It serves via gunicorn
https://github.com/linuxserver/docker-babybuddy/blob/main/root/etc/services.d/babybuddy/run#L13

**Comment by adjokic** [comment]
Thanks for pointing that out.
After some digging, I was able to get it to work with:
```
exec \
    s6-setuidgid abc gunicorn babybuddy.wsgi \
        --env SCRIPT_NAME="/babybuddy" \
        --bind :8000 --log-level=debug \
        --worker-tmp-dir=/dev/shm --log-file=- \
        --workers=2 --threads=4 --worker-class=gthread
```
However, this seems to break static files.

**Comment by adjokic** [comment]
I had to add both SCRIPT_NAME and SUB_PATH, and was able to make it work with the following configuration:
```
version: "2.1"
services:
  babybuddy:
    image: lscr.io/linuxserver/babybuddy
    container_name: babybuddy
    environment:
      - TZ=UTC
      - USE_24_HOUR_TIME_FORMAT=true
      - SCRIPT_NAME=/babybuddy
      - SUB_PATH=babybuddy
      - CSRF_TRUSTED_ORIGINS=https://mydomain.com
    volumes:
      - ~/docker-data/babybuddy:/config
    ports:
      - 8000:8000
    restart: unless-stopped
```
and the following `apache.conf`:
```
ProxyPass                    /babybuddy/static       http://${INTERNAL_SERVER}:8000/babybuddy/babybuddy/static
ProxyPass                    /babybuddy                 http://${INTERNAL_SERVER}:8000/babybuddy
ProxyPassReverse        /babybuddy/static       http://${INTERNAL_SERVER}:8000/babybuddy/babybuddy/static
ProxyPassReverse        /babybuddy                 http://${INTERNAL_SERVER}:8000/babybuddy
ProxyPass                    /babybuddy/static/      http://${INTERNAL_SERVER}:8000/babybuddy/babybuddy/static/
ProxyPass                    /babybuddy/                http://${INTERNAL_SERVER}:8000/babybuddy/
ProxyPassReverse        /babybuddy/static/      http://${INTERNAL_SERVER}:8000/babybuddy/babybuddy/static/
ProxyPassReverse        /babybuddy/                http://${INTERNAL_SERVER}:8000/babybuddy/
```
