### ISSUE TITLE
Connection refused with v1.10.2-ls31

### ISSUE THREAD

**Issue by danepowell** [linuxserver/docker-babybuddy#18]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

v1.10.2-ls30 works fine, I expected v1.10.2-ls31 to have no breaking changes.

## Current Behavior

Attempting to view Baby Buddy with v1.10.2-ls31 results in "connection refused" and nothing else in the logs. Seems like a regression introduced by https://github.com/linuxserver/docker-babybuddy/pull/17

## Steps to Reproduce

1. Launch Baby Buddy behind Traefik using `docker-compose.yml` below
2. Attempt to visit Baby Buddy at `https://babybuddy.${LOCALDOMAIN}`
3. Get a 502, Bad Gateway
4. Check Traefik debug logs, see that the backend refused the connection

There is nothing in the Baby Buddy logs about the refused connection, so I'm not sure how to proceed with debugging.

## Environment
**OS:** Ubuntu
**CPU architecture:** x86_64
**How docker service was installed:** snap

docker-composer.yml
```yaml
version: '3'
services:
  babybuddy:
    # v1.10.2-ls31 is broken, not sure why
    image: linuxserver/babybuddy:v1.10.2-ls31
    container_name: babybuddy
    environment:
      DEBUG: "True"
      TZ: ${TZ}
      CSRF_TRUSTED_ORIGINS: https://babybuddy.${LOCALDOMAIN}
      SECURE_PROXY_SSL_HEADER: "True"
    volumes:
      - ${CONFIGFOLDER}/babybuddy:/config
    networks:
      - web
    labels:
      traefik.enable: true
      traefik.http.routers.babybuddy.entrypoints: web-secure
      traefik.http.routers.babybuddy.middlewares: default@file
      traefik.http.routers.babybuddy.rule: Host(`babybuddy.${LOCALDOMAIN}`)
      traefik.http.routers.babybuddy.tls.certResolver: primary
    restart: ${RESTARTPOLICY}
```

## Command used to create docker container (run/create/compose/screenshot)

docker-compose up -d

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 02-tamper-check: executing...
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
BabyBuddy: https://github.com/sponsors/cdubz

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-config: executing...
Operations to perform:
  Apply all migrations: admin, auth, authtoken, axes, babybuddy, contenttypes, core, sessions
Running migrations:
  No migrations to apply.
  Your models in app(s): 'babybuddy' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
Cache table 'cache_default' already exists.
[cont-init.d] 30-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-04-06 10:59:00 -0700] [376] [INFO] Starting gunicorn 20.1.0
[2022-04-06 10:59:00 -0700] [376] [INFO] Listening at: http://127.0.0.1:3000 (376)
[2022-04-06 10:59:00 -0700] [376] [INFO] Using worker: gthread
[2022-04-06 10:59:00 -0700] [404] [INFO] Booting worker with pid: 404
[2022-04-06 10:59:00 -0700] [405] [INFO] Booting worker with pid: 405
```
